#!/bin/bash

# Interactive API key setup script

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Competitive Insights - API Key Setup${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

# Check if .env exists
if [ -f .env ]; then
    echo -e "${YELLOW}⚠ .env file already exists${NC}"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo -e "\n${BLUE}You can manually edit .env file instead.${NC}\n"
        exit 0
    fi
fi

# Create/overwrite .env
cat > .env << 'EOF'
# Competitive Insights - API Configuration
# Generated by setup script

EOF

echo -e "${BLUE}Let's configure your API keys.${NC}"
echo -e "${YELLOW}Leave blank to skip a service (you can add it later)\n${NC}"

# SimilarWeb
echo -e "${BLUE}━━━ SimilarWeb ━━━${NC}"
echo "Get your key at: https://account.similarweb.com/api-management"
echo "Required plan: API-only, Business, or Enterprise"
read -p "SimilarWeb API Key (or press Enter to skip): " sw_key
echo "SIMILARWEB_API_KEY=${sw_key}" >> .env
echo ""

# Ahrefs
echo -e "${BLUE}━━━ Ahrefs ━━━${NC}"
echo "Get your key at: https://ahrefs.com/api"
echo "Note: Use API v3 keys, not MCP keys"
read -p "Ahrefs API Key (or press Enter to skip): " ah_key
echo "AHREFS_API_KEY=${ah_key}" >> .env
echo ""

# SEMRush
echo -e "${BLUE}━━━ SEMRush ━━━${NC}"
echo "Get your key at: https://www.semrush.com/api-analytics/"
echo "Required plan: SEO Business or Trends Basic/Premium"
read -p "SEMRush API Key (or press Enter to skip): " sr_key
echo "SEMRUSH_API_KEY=${sr_key}" >> .env
echo ""

# Mock data setting
echo -e "${BLUE}━━━ Data Mode ━━━${NC}"
if [[ -n "$sw_key" || -n "$ah_key" || -n "$sr_key" ]]; then
    read -p "Use real API data? (Y/n): " use_real
    if [[ $use_real =~ ^[Nn]$ ]]; then
        echo "USE_MOCK_DATA=true" >> .env
    else
        echo "USE_MOCK_DATA=false" >> .env
    fi
else
    echo "USE_MOCK_DATA=true" >> .env
fi

# Add optional settings
cat >> .env << 'EOF'

# Optional: Cache and Rate Limiting
API_CACHE_TTL_SECONDS=300
API_RATE_LIMIT_PER_SECOND=10
EOF

echo -e "\n${GREEN}✓ .env file created successfully!${NC}\n"

# Count configured keys
configured=0
[[ -n "$sw_key" ]] && ((configured++))
[[ -n "$ah_key" ]] && ((configured++))
[[ -n "$sr_key" ]] && ((configured++))

echo -e "${BLUE}Summary:${NC}"
echo "Configured services: $configured/3"
echo ""

if [ $configured -gt 0 ]; then
    echo -e "${GREEN}Next steps:${NC}"
    echo "1. Test your configuration: npm run test-mcp"
    echo "2. Run an audit: npm run audit example.com competitor.com"
else
    echo -e "${YELLOW}No API keys configured.${NC}"
    echo "The tool will use mock data for testing."
    echo ""
    echo "To add API keys later, run this script again or edit .env manually."
fi

echo ""
